import Head from "next/head";
import Image from "next/image";
import HeadNav from "../components/HeadNav";
import Collapse from "../components/collapseContent";


export default function Home() {
    return (
        <div>
            <Head>
                <title>Hola Mundo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeadNav />
            <main>
                <div className="screen__dashboard wrapper">
                    <div className="dashboard__main">
                        <div className="dashboard__head">
                            <h1 className="h1">
                                Bienvenido, <br /> Juan José Perdomo
                            </h1>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit. Etiam sit amet scelerisque
                                mauris. Pellentesque elementum elementum lectus,
                                ut iaculis sem tincidunt commodo. Ut a malesuada
                            </p>
                        </div>
                        <div className="dashboard__content">
                            <Collapse/>
                        </div>
                    </div>
                    <div className="dashboard__aside">
                        <div className="dashboard__head">
                            <h1>Bienvenido</h1>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
