import Head from "next/head";
import Image from "next/image";
import HeadNav from "../components/HeadNav";
import Collapse from "../components/collapseContent";
import ImageUser from "../components/ImageUser";
import { educacion as educationArray } from "../data/example"
import EducationInfo from "../components/EducationInfo";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Hola Mundo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeadNav />
            <main>
                <div className="screen__dashboard wrapper">
                    <div className="dashboard__main">
                        <div className="dashboard__head">
                            <h1 className="h1">
                                Bienvenido, <br /> Juan José Perdomo
                            </h1>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur
                                adipiscing elit. Etiam sit amet scelerisque
                                mauris. Pellentesque elementum elementum lectus,
                                ut iaculis sem tincidunt commodo. Ut a malesuada
                            </p>
                        </div>
                        <div className="dashboard__content">
                            <Collapse title="Perfil profesional">
                                <p>
                                    Lorem ipsum dolor sit amet consectetur
                                    adipisicing elit. Distinctio eum quaerat
                                    quia excepturi cumque, iste molestiae, saepe
                                    veritatis aliquid tempora veniam laudantium.
                                    Consequatur, quo possimus nihil aspernatur
                                    id vel itaque?
                                </p>
                            </Collapse>
                            <Collapse title="Educación" variant="education">
                               {
                                    educationArray.map((info, idx) => 
                                        // [item0, item1, item2] -- idx: 0, 1, 2
                                        // educationArray.length - 1 : Ultimo elemento del array
                                        // Devuelve: True, True, False
                                        <EducationInfo info={info} key={info._id} divider={educationArray.length - 1 !== idx}/>
                                    )
                               }
                            </Collapse>
                        </div>
                    </div>
                    <div className="dashboard__aside">
                        <ImageUser />
                    </div>
                </div>
            </main>
        </div>
    );
}
