import Head from "next/head";
import Image from "next/image";
import HeadNav from "../components/HeadNav";
import Inputs from "../components/Inputs";
import loginPhoto from "../public/img/loginimage.png";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Hola Mundo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeadNav />
            <main>
                <div className="screen__login wrapper">
                    <div className="info__login screen__padding">
                        <h1 className="h1">
                            ¡Crea tu hoja de vida de forma rápida y sencilla!
                        </h1>
                        <Image src={loginPhoto}/>
                        <h2 className="h2">Sed ut perspiciatis</h2>
                        <p>
                            Nemo enim ipsam voluptatem quia voluptas sit
                            aspernatur aut odit aut fugit, sed quia consequuntur
                            magni dolores eos qui ratione voluptatem sequi
                            nesciunt. Neque porro quisquam est.
                        </p>
                    </div>
                    <div class="form__login">
                        <div class="form__container">
                            <div class="form__header">
                                <h3>Registra tu perfil</h3>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur
                                    adipiscing elit. Etiam sit amet scelerisque
                                    mauris. Pellentesque elementum, si ya tienes
                                    cuenta <a href="">ingresa aquí</a>
                                </p>
                            </div>
                            <div class="form__box">
                                <form action="">
                                    <Inputs
                                        name="Nombres"
                                        id="name_login"
                                        type="text"
                                    />
                                    <Inputs
                                        name="Apellidos"
                                        id="lastname_login"
                                        type="text"
                                    />
                                    <Inputs
                                        name="Correo"
                                        id="email_login"
                                        type="email"
                                    />
                                    <Inputs
                                        name="Contraseña"
                                        id="email_login"
                                        type="password"
                                    />
                                    <div class="button__submit">
                                        <button
                                            class="btn-nx btn-nx-primary"
                                            type="submit"
                                        >
                                            Registrarse
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}
